apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aryon-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ido-Ozeri/aryon-app.git
    targetRevision: master
    path: charts/aryon-app
  destination:
    server: https://kubernetes.default.svc
    namespace: aryon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
