{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ $service.port | default 80 }}
      targetPort: {{ $service.targetPort | default "http" }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
